### ISSUE TITLE
Inconsistent Date Results on macOS vs. Linux for Swift Code Calculating Current Month Range

### ISSUE THREAD

**Issue by MartinLau7** [swiftlang/swift-foundation#1017]
The code below produces different results when run on macOS and Linux. 
On macOS, it returns `2024-10-01` for the first day of the month and `2024-10-31` for the last day. 
However, on Linux, it returns `2024-09-30` for the first day and `2024-10-30` for the last day.

```swift
private func getCurrentMonthRange() -> (start: String, end: String) {
    let today = Date()
    let calendar = Calendar.current

    let firstDayComponents = calendar.dateComponents([.year, .month], from: today)
    let firstDay = calendar.date(from: firstDayComponents)!

    var lastDayComponents = DateComponents()
    lastDayComponents.month = 1
    lastDayComponents.day = -1
    let lastDay = calendar.date(byAdding: lastDayComponents, to: firstDay)!

    let dateFormatter = DateFormatter()
    dateFormatter.locale = Locale(identifier: "en_US_POSIX")
    dateFormatter.timeZone = TimeZone(secondsFromGMT: 0)
    dateFormatter.dateFormat = "yyyy-MM-dd"
    return (start: dateFormatter.string(from: firstDay), end: dateFormatter.string(from: lastDay))
}
let (start, end) = getCurrentMonthRange()
print("first day of month: \(start), last day of month: \(end)")
```

**Comment by itingliu** [comment]
`calendar.date(from:)` converts the date component into a `Date` using the given calendar's time zone, so if `Calendar.current.timeZone` on your Linux machine and mac machine are different, `firstDay` would be different. 

On top of that, I believe there's also a discrepancy that you're calculating a date from `Calendar.current.timeZone`, but later formatted into GMT. You'd want to use the same calendar and time zone for both calculation and formatting.

Since it looks like you want the eventual result to always be represented in GMT, I think it makes sense to use a fixed calendar instead of `.current` as well as setting its `timeZone` so everything is aligned. Something like this
```swift
let calendar = Calendar.current
```

With 
```swift
var calendar = Calendar(identifier: .gregorian)
calendar.timeZone = .gmt
```

Or the other way around, i.e. setting `dateFormatter`'s calendar and time zone to the one you used for calculation

**Comment by MartinLau7** [comment]
> `calendar.date(from:)` converts the date component into a `Date` using the given calendar's time zone, so if `Calendar.current.timeZone` on your Linux machine and mac machine are different, `firstDay` would be different.
> 
> On top of that, I believe there's also a discrepancy that you're calculating a date from `Calendar.current.timeZone`, but later formatted into GMT. You'd want to use the same calendar and time zone for both calculation and formatting.
> 
> Since it looks like you want the eventual result to always be represented in GMT, I think it makes sense to use a fixed calendar instead of `.current` as well as setting its `timeZone` so everything is aligned. Something like this
> 
> ```swift
> let calendar = Calendar.current
> ```
> 
> With
> 
> ```swift
> var calendar = Calendar(identifier: .gregorian)
> calendar.timeZone = .gmt
> ```
> 
> Or the other way around, i.e. setting `dateFormatter`'s calendar and time zone to the one you used for calculation

Thank you, for the reminder. There is a difference between the time zones in Linux and macOS, and I overlooked this issue.
