### ISSUE TITLE
Many url(for:in:appropriateFor:create:) calls throw Error on Windows

### ISSUE THREAD

**Issue by jakepetroules** [swiftlang/swift-foundation#1048]
This crashes on Windows:

FileManager.default.url(for: .libraryDirectory, in: .userDomainMask, appropriateFor: nil, create: false)

Swift/ErrorType.swift:253: Fatal error: Error raised at top level: (extension in Foundation):FoundationEssentials.FileManager.(unknown context at $7ffe36188798).URLForDirectoryError.directoryUnknown

due to most locations being unimplemented. Presumably this should return some fallback location instead of crashing.

Swift version 6.1-dev (LLVM 5728735dd595a22, Swift a680211a4f8d4dc)
Target: x86_64-unknown-windows-msvc

**Comment by jmschonfeld** [comment]
> Presumably this should return some fallback location instead of crashing.

I'm not sure I agree with this as I don't think it'd be appropriate for Foundation to decide where such a fallback location might live.

To clarify, this function doesn't crash but rather it `throw`s an error, it looks like your application is crashing because you have a `try` at the top level of an executable without a `do`/`catch` block which is defined to fatal error upon a thrown error. IMO it seems reasonable that if a directory/mask is provided that doesn't exist on the current platform that this API should throw an error indicating it was unable to produce a URL, and the client can then choose a suitable fallback behavior. It's possible this could be improved by indicating which `SearchPathDirectory` cases are valid on certain platforms if a platform doesn't have the concept of a directory entirely, but it's also possible that a directory is applicable to a platform but it does not exist or isn't created for the specified user and therefore cannot be returned.

@jakepetroules do you think adding failure logic to your client application to determine what a suitable fallback location might be for your application would be a good solution here? Or is there anything that is requiring you to escalate this thrown error to a crash in your application?

**Comment by jakepetroules** [comment]
Looks like you're right. I might've been thinking of a different function which was non-throwing and wouldn't have been able to throw an error..
