### ISSUE TITLE
URL resolution of a relative path on a base produces invalid URL

### ISSUE THREAD

**Issue by ptsochantaris** [swiftlang/swift-foundation#1062]
A simple example can demonstrate this issue:

```
import Cocoa

let base = URL(string: "https://apple.com/basepath")!

let resolved = URL(string: "../relativepath", relativeTo: base)!

print(resolved.absoluteString)
```

- Expected result: `https://apple.com/relativepath`
- Actual result: `https://apple.com/../relativepath` which is an invalid URL.

**Comment by thematver** [comment]
Hi! This isn’t a bug — it’s actually the intended behavior, which follows [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt).

When you create a relative URL like `../relativepath` using a base URL like `https://apple.com/basepath`, Swift resolves it correctly to `https://apple.com/../relativepath`. This might seem odd, but it works the such way because the `..` segment is valid in a URL and is kept intact for possible further processing.

If you do need the URL to be fully resolved (so that `https://apple.com/basepath` + `../relativepath` becomes `https://apple.com/relativepath`), you can use the `.standardized` property to normalize it:

```
let base = URL(string: "https://apple.com/basepath")!
let resolved = URL(string: "../relativepath", relativeTo: base)!.standardized // will be: https://apple.com/relativepath
```

Hope this helps!

**Comment by ptsochantaris** [comment]
Thanks @thematver I really appreciate that info - I didn't know about `standardized` at all.

I guess can close this now, thanks again!
